openapi: 3.1.0
info:
  title: Europe Countries
  description: List of countries in Europe
  version: 1.0.0
components:
  schemas:
    country:
      type: string
      enum:
        - Austria
        - Belgium
        - Bulgaria
        - Croatia
        - Cyprus
        - Czechia
        - Denmark
        - Estonia
        - Finland
        - France
        - Germany
        - Greece
        - Hungary
        - Ireland
        - Italy
        - Latvia
        - Lithuania
        - Luxembourg
        - Malta
        - Netherlands
        - Poland
        - Portugal
        - Romania
        - Slovakia
        - Slovenia
        - Spain
        - Sweden
